name: 🐛 Problem / Content Issue
description: Report an error, incorrect explanation, or code issue.
title: "[Bug] Short description of the issue"
labels: ["bug"]
body:
  - type: input
    id: page
    attributes:
      label: Problem Page URL
      description: Paste the full URL of the problem page.
      placeholder: https://algo.ppradosh.com/month-1/week-1/...
    validations:
      required: true

  - type: textarea
    id: issue_description
    attributes:
      label: What is the issue?
      description: Clearly describe what seems incorrect or unclear.
      placeholder: Explain the issue in detail.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Suggested Correction (Optional)
      description: If you have a proposed correction, provide it here.

  - type: textarea
    id: additional
    attributes:
      label: Additional Context (Optional)
      description: Add references, screenshots, or explanation if helpful.