name: 🚀 Feature Request
description: Suggest a new feature or structural improvement for Algorithm Logbook.
title: "[Feature] Short descriptive title"
labels: ["feature"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting an improvement to Algorithm Logbook.
        Please keep requests focused on educational value and structural clarity.

  - type: textarea
    id: feature_description
    attributes:
      label: What feature would you like to see?
      description: Clearly describe the proposed feature.
      placeholder: Explain the feature in detail.
    validations:
      required: true

  - type: textarea
    id: problem_statement
    attributes:
      label: What problem does this solve?
      description: Explain why this feature is necessary or beneficial.
      placeholder: Describe the current limitation or gap.
    validations:
      required: true

  - type: textarea
    id: proposed_solution
    attributes:
      label: Proposed Approach (Optional)
      description: If you have an idea for implementation, describe it here.

  - type: dropdown
    id: feature_type
    attributes:
      label: Feature Category
      options:
        - UI / UX Improvement
        - Navigation Enhancement
        - Educational Content Structure
        - Performance Optimization
        - Accessibility
        - SEO / Metadata
        - Other
    validations:
      required: true

  - type: checkboxes
    id: confirmation
    attributes:
      label: Confirmation
      options:
        - label: This feature aligns with the educational and minimal philosophy of the site.
          required: true